/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#052920',
        'primary-container': '#1E3F35',
        'primary-fixed': '#C6EBDC',
        'primary-fixed-dim': '#AACEC0',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#87AA9D',
        'on-primary-fixed': '#002018',
        'on-primary-fixed-variant': '#2C4D42',
        secondary: '#8A496A',
        'secondary-container': '#FFAFD4',
        'secondary-fixed': '#FFD8E8',
        'secondary-fixed-dim': '#FFAFD4',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#7C3E5E',
        'on-secondary-fixed': '#390525',
        'on-secondary-fixed-variant': '#6E3252',
        tertiary: '#242420',
        'tertiary-container': '#3A3935',
        'tertiary-fixed': '#E5E2DB',
        'tertiary-fixed-dim': '#C9C6C0',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#A4A39C',
        'on-tertiary-fixed': '#1C1C18',
        'on-tertiary-fixed-variant': '#474742',
        error: '#BA1A1A',
        'error-container': '#FFDAD6',
        'on-error': '#FFFFFF',
        'on-error-container': '#93000A',
        surface: '#F8FAF5',
        'surface-dim': '#D9DBD6',
        'surface-bright': '#F8FAF5',
        'surface-variant': '#E1E3DF',
        'surface-tint': '#44655A',
        'surface-container': '#EDEEEA',
        'surface-container-low': '#F2F4F0',
        'surface-container-high': '#E7E9E4',
        'surface-container-highest': '#E1E3DF',
        'surface-container-lowest': '#FFFFFF',
        'on-surface': '#191C1A',
        'on-surface-variant': '#414845',
        outline: '#717975',
        'outline-variant': '#C1C8C4',
        background: '#F8FAF5',
        'on-background': '#191C1A',
        'inverse-surface': '#2E312E',
        'inverse-on-surface': '#F0F1ED',
        'inverse-primary': '#AACEC0',
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
    },
  },
  plugins: [],
};
